'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./elements/Header";
import Footer from "./elements/Footer";
import store from "@/redux/store";
import { Provider } from 'react-redux';
import LayoutWrapper from "./LayoutWrapper";
import AuthProvider from "./providers/AuthProvider";
import { Toaster } from "sonner";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   <head>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"></link>
   </head>
      <body
      > <Provider store={store}>    
        <LayoutWrapper>
            <AuthProvider>
          {children}
           <Toaster richColors position="top-right" />
          </AuthProvider>
        </LayoutWrapper>
      </Provider>  
      </body>
    </html>
  );
}
